config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "rooms/index"
  root to: 'toppage#index'
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:new, :create, :destroy] do
    resources :charas
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chara.rb
class Chara < ApplicationRecord
  belongs_to :user
  belongs_to :room, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :content, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users  
  has_many :messages, dependent: :destroy
  has_many :charas

  validates :name, presence: true
  
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :charas
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/charas_controller.rb
class CharasController < ApplicationController
  before_action :set_chara, only: [:show, :edit, :update, :destroy]
  before_action :set_room

  def index
  end

  def show
    @chara = Chara.new
    @charas = @room.charas
  end

  def new
    @chara = Chara.new
  end

  def create
    @chara = Chara.new(chara_params)
    if @chara.save
      redirect_to room_messages_path(@room)
    else
      render :new
    end
  end

  def destroy
    @chara = Chara.find(params[:id])
    @chara.destroy
    redirect_to :room
  end

  private

  def set_chara
    @chara = Chara.find(params[:id])
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def chara_params
    params.require(:chara).permit(:name, :job, :magic, :hitpoint, :attack, :defence, :escape, :image).merge(user_id: current_user.id, room_id: params[:room_id])
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @room = Room.find(params[:room_id])
    @message = Message.new
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
  
end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charas/new.html.erb
<div class='chat-room-form'>
  <h1>新規キャラクター</h1>
  <%=form_with model: [@room, @chara], local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :キャラ名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: '入力してください'%>
      </div>
    </div>
        <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :職業, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :job, class: 'chat__room_name chat-room-form__input', placeholder: '入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :魔法, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :magic, class: 'chat__room_name chat-room-form__input', placeholder: '入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :体力, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :hitpoint, class: 'chat__room_name chat-room-form__input', placeholder: '入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :攻撃力, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :attack, class: 'chat__room_name chat-room-form__input', placeholder: '入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :防御力, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :defence, class: 'chat__room_name chat-room-form__input', placeholder: '入力してください'%>
      </div>
    </div>
        <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :回避力, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :escape, class: 'chat__room_name chat-room-form__input', placeholder: '入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :アイコン, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, class: 'chat__room_name chat-room-form__input', placeholder: '入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/charas/show.html.erb
    <% @charas.each do |chara| %>
      <li>
        <%= "#{chara.user.name}さん 使用PC = "%>
        <%= "名前:" %>
        <span id="chara-name"><%="#{chara.name}"%></span>
        <%= "職業:#{chara.job}"%>
        <%= "魔法:#{chara.magic}"%>
        <%= "HP:" %>
        <span id="chara-hp"><%="#{chara.hitpoint}"%></span>
        <%= "攻撃力:#{chara.attack}"%>
        <%= "防御力:#{chara.defence}"%>
        <%= "回避:#{chara.escape}"%>
        <p>
        <%#<%= link_to "編集", edit_room_chara_path(chara), method: :get %><%# or <%= link_to "削除", room_chara_path(chara), method: :delete %>
        </p>
      </li>
    <% end %>

  <div class="chara-list">
  <p>戦闘処理</p>
    <div>
      <div class="fight-section">
        <ul class="nav-lists">
          <span id="lists-current-user" class="nav__btn">ユーザーの選択</span>
          <li class="list-status">
            現在の選択；
            <span id="current-select-user">選択されていません</span>
          </li>
        </ul>
        <ul class="show-lists hidden" id="pull-down-current-user">
          <li class="pull-down-current-user" id="current-select-user1">User1</li>
          <li class="pull-down-current-user" id="current-select-user2">User2</li>
        </ul>
        <%= current_user.name %>さんは<span id="your-user">User1 or User2</span>です
      </div>
      <div class="fight-section">
        <ul class="nav-lists">
          <span id="lists" class="nav__btn">戦闘行動の選択</span>
          <li class="list-status">
            現在の選択；
            <span id="current-list">選択されていません</span>
          </li>
        </ul>
        <ul class="show-lists hidden" id="pull-down">
          <li class="pull-down-list" id="attack">攻撃</li>
          <li class="pull-down-list" id="defence">防御</li>
          <li class="pull-down-list" id="escape">回避</li>
          <li class="pull-down-list" id="reset">リセット</li>
        </ul>
      </div>
      <div class="fight-section">
        <ul class="nav-lists">
          <span id="lists-user" class="nav__btn">対象の選択</span>
          <li class="list-status">
            現在の選択；
            <span id="current-list-user">選択されていません</span>
          </li>
        </ul>
        <ul class="show-lists hidden" id="pull-down-user">
          <li class="pull-down-list-user" id="select-user1">User1</li>
          <li class="pull-down-list-user" id="select-user2">User2</li>
        </ul>
      </div>
      <div class="right">
        <span class="battle-btn" id="action">実行</span>
      </div>
      <p>※上手く読み込まれない場合はReload(再読み込み)をお試しください</p>
      <div class="fight-section">
        <li>
          <span id="your-user">User1</span> HP<input type="number" id="user1-hp" value="100" max="100" min="0">
          <span id="your-user">User2</span> HP<input type="number" id="user2-hp" value="100" max="100" min="0">
        </li>
      </div>
    </div>
  </div>

  <div class="fight-log">
    <div id="fight-log-message" class="fight-log-message"></div>
  </div>

    <%# <table>
      <tbody>
        <tr>
          <th>キャラクター名</th>
          <td class="detail-value"></td>
        </tr>
        <tr>
          <th>職業</th>
          <%#<td class="detail-value"></td>
        </tr>
        <tr>
          <th>魔法属性</th>
          <%#<td class="detail-value"></td>
        </tr>
        <tr>
          <th>HP</th>
          <%#<td class="detail-value"></td>
        </tr>
        <tr>
          <th>攻撃力</th>
          <%#<td class="detail-value"></td>
        </tr>
        <tr>
          <th>防御力</th>
          <%#<td class="detail-value"></td>
        </tr>
        <tr>
          <th>回避力</th>
          <%#<td class="detail-value"></td>
        </tr>
      </tbody>
    </table> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NrpgSession</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>
  <div class="navbar">
  </div>

<div id="info-message"></div>

<div class="messages" id="chat-messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
      <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>
  <div class="header-name">
      <%= link_to "トップページにもどる", root_path(current_user) %><br>
      <br>
      <%= link_to "キャラクター作成", "/rooms/#{@room.id}/charas/new", target: :_blank %><br>
      <br>
      <%= link_to "ステータス一覧・ダメージ計算", "/rooms/#{@room.id}/charas/#{current_user.id}", target: :_blank %>
      <span class="attention">※必ずキャラクター作成を行なってください</span>
  </div>
</div>
<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden">
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
            <option value="">チャットするユーザーを選択してください</option>
            <% User.where.not(id: current_user.id).each do |user| %>
              <option value=<%= user.id %>><%= user.name %></option>
            <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden">
      </div>
      <input name="room[user_ids][]" value=<%= current_user.id %> type="hidden">
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>
  <%#= form_with model: User.new, method: :get, class: "search__form" do |f| %>
      <%#= f.text_field :name, required: true, class: "search__form__input" %>
      <%#= f.submit "検索" %>
  <%# end %>
  <%#= form_with(url: search_users_path, local: true, method: :get) do |form| %>
  <%#= form.text_field :name, placeholder: "投稿を検索する"%>
  <%#= form.submit "検索" %>
<%# end %>
  <%# @users.each do |user| %>
    <%#= user.name %>
  <%# end %>

app/views/toppage/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>NRPG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            NRPG
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "部屋作成", new_room_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <main class="main">
    <div class="inner">
      <%# ログインしているときは以下を表示する %>
      <% if user_signed_in? %>
        <div class="greeting">
          <%= link_to "#{current_user.name}さん", edit_user_path(current_user), class: :greeting__link %>
          <%= "のセッションルーム" %>
        </div>
      <% end %>
      <%# // ログインしているときは上記を表示する %>
      <div class="card__wrapper">
        <% current_user.rooms.each do |room| %>
          <div class="card">
            <div class="card__body">
              <%= link_to room.name, room_messages_path(room) %>
            </div>
              <%= link_to "#", room_messages_path(room) %>
          </div>
        <% end %>
      </div>
    </div>
    </main>
    <footer class="footer">
      <p class="copyright">Copyright © NRPG All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>